apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudtype-sa
imagePullSecrets:
  - name: reg-cloudtype
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudtype-agent
imagePullSecrets:
  - name: reg-cloudtype
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudtype-builder
imagePullSecrets:
  - name: reg-cloudtype
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudtype-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cloudtype-agent
    namespace: cloudtype